package model;
// Generated Dec 4, 2009 10:06:39 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account", schema = "public")
public class Account implements java.io.Serializable {

	private int id;
	private String firstname;
	private String lastname;
	private Boolean unixcreated;
	private String username;
	private String password;
	private Date lastlogin;
	private Float logincredits;
	private Float loginused;
	private Integer printcredits;
	private Integer printpagesused;
	private Set<UserInRole> userInRoles = new HashSet<UserInRole>(0);

	public Account() {
	}

	public Account(int id) {
		this.id = id;
	}
	public Account(int id, String firstname, String lastname,
			Boolean unixcreated, String username, String password,
			Date lastlogin, Float logincredits, Float loginused,
			Integer printcredits, Integer printpagesused,
			Set<UserInRole> userInRoles) {
		this.id = id;
		this.firstname = firstname;
		this.lastname = lastname;
		this.unixcreated = unixcreated;
		this.username = username;
		this.password = password;
		this.lastlogin = lastlogin;
		this.logincredits = logincredits;
		this.loginused = loginused;
		this.printcredits = printcredits;
		this.printpagesused = printpagesused;
		this.userInRoles = userInRoles;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "firstname", length = 15)
	@Length(max = 15)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", length = 15)
	@Length(max = 15)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "unixcreated")
	public Boolean getUnixcreated() {
		return this.unixcreated;
	}

	public void setUnixcreated(Boolean unixcreated) {
		this.unixcreated = unixcreated;
	}

	@Column(name = "username", length = 8)
	@Length(max = 8)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 8)
	@Length(max = 8)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "lastlogin", length = 13)
	public Date getLastlogin() {
		return this.lastlogin;
	}

	public void setLastlogin(Date lastlogin) {
		this.lastlogin = lastlogin;
	}

	@Column(name = "logincredits", precision = 8, scale = 8)
	public Float getLogincredits() {
		return this.logincredits;
	}

	public void setLogincredits(Float logincredits) {
		this.logincredits = logincredits;
	}

	@Column(name = "loginused", precision = 8, scale = 8)
	public Float getLoginused() {
		return this.loginused;
	}

	public void setLoginused(Float loginused) {
		this.loginused = loginused;
	}

	@Column(name = "printcredits")
	public Integer getPrintcredits() {
		return this.printcredits;
	}

	public void setPrintcredits(Integer printcredits) {
		this.printcredits = printcredits;
	}

	@Column(name = "printpagesused")
	public Integer getPrintpagesused() {
		return this.printpagesused;
	}

	public void setPrintpagesused(Integer printpagesused) {
		this.printpagesused = printpagesused;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "account")
	public Set<UserInRole> getUserInRoles() {
		return this.userInRoles;
	}

	public void setUserInRoles(Set<UserInRole> userInRoles) {
		this.userInRoles = userInRoles;
	}

}
