package model;
// Generated Dec 4, 2009 10:06:39 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Userrole generated by hbm2java
 */
@Entity
@Table(name = "userrole", schema = "public")
public class Userrole implements java.io.Serializable {

	private int id;
	private String name;
	private Set<UserInRole> userInRoles = new HashSet<UserInRole>(0);

	public Userrole() {
	}

	public Userrole(int id) {
		this.id = id;
	}
	public Userrole(int id, String name, Set<UserInRole> userInRoles) {
		this.id = id;
		this.name = name;
		this.userInRoles = userInRoles;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 8)
	@Length(max = 8)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "userrole")
	public Set<UserInRole> getUserInRoles() {
		return this.userInRoles;
	}

	public void setUserInRoles(Set<UserInRole> userInRoles) {
		this.userInRoles = userInRoles;
	}

}
