package model;
// Generated Dec 4, 2009 10:06:39 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * UserInRole generated by hbm2java
 */
@Entity
@Table(name = "user_in_role", schema = "public")
public class UserInRole implements java.io.Serializable {

	private static final long serialVersionUID = -1226728322100990451L;
	private int id;
	private Userrole userrole;
	private Account account;

	public UserInRole() {
	}

	public UserInRole(int id) {
		this.id = id;
	}
	public UserInRole(int id, Userrole userrole, Account account) {
		this.id = id;
		this.userrole = userrole;
		this.account = account;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role")
	public Userrole getUserrole() {
		return this.userrole;
	}

	public void setUserrole(Userrole userrole) {
		this.userrole = userrole;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account")
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

}
