#!/bin/sh -e

# Read the restricted workstations list, crank out the brconfig file, and tell pf

IF=XXX0

RESTRICTEDLIST="/etc/restrictedworkstations"

BRCONFIG=/etc/hostname.bridge0

NEWCONFIG=$(mktemp)
echo add ${IF} > ${NEWCONFIG}

while read macaddr hash location
do
	case ${macaddr} in
		'#')	;;
		*)	
		echo "rule pass in on ${IF} src ${macaddr} tag Restricted" >> ${NEWCONFIG}
		;;
	esac
done < ${RESTRICTEDLIST}

cp ${BRCONFIG} ${BRCONFIG}.bak

cp ${NEWCONFIG} ${BRCONFIG}

sh /etc/netstart bridge0
