#!/bin/sh

set -x

# This will actually print a page, at least at Ernescliff
env DEVICE_URI=usermgmt://socket://192.168.100.251:9100 cupsaccountfilter.py 123 ian test.ps 1 - testdata && exit

# test for no arguments
cupsaccountfilter.py

# test for wrong # args
cupsaccountfilter.py foo

# test that unknown account failure works
env DEVICE_URI=usermgmt://ipp://1.1.1.1/lpr cupsaccountfilter.py 123 jjjjjjj test.ps 1 - testdata

# test that account balance failure works
env DEVICE_URI=usermgmt://ipp://1.1.1.1/lpr cupsaccountfilter.py 123 testfail test.ps 1 - testdata

# test that we get as far as trying the next filter
env DEVICE_URI=usermgmt://ipp://1.1.1.1/p1 cupsaccountfilter.py 123 ian test.ps 1 - testdata

# test that we invoke the next filter
env DEVICE_URI=usermgmt://ipp://1.1.1.1/localhost:1234 cupsaccountfilter.py 123 ian test.ps 1 - testdata
